DROP TABLE IF EXISTS smallvehicles2;

CREATE TABLE smallvehicles2 (
  id SERIAL PRIMARY KEY NOT NULL,
  smallvehicles2_uid UUID NOT NULL UNIQUE,
  iot_token VARCHAR(300) NOT NULL,
  small_vehicle INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (iot_token) REFERENCES systems (iot_token)
)