DROP TABLE IF EXISTS vehicles;

CREATE TABLE vehicles (
  system_uid UUID NOT NULL,
  speed
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)