DROP TABLE IF EXISTS vehicles1;

CREATE TABLE vehicles1 (
  id SERIAL PRIMARY KEY NOT NULL,
  vehicles1_uid UUID NOT NULL UNIQUE,
  iot_token VARCHAR(300) NOT NULL,
  vehicle INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (iot_token) REFERENCES systems (iot_token)
)